springdoc:
  show-actuator: 'true'
  swagger-ui:
    oauth:
      additional-query-string-params:
        nonce: abc
  paths-to-match: /api/**, /actuator/info, /actuator/health, /actuator/permissions
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: password
    username: sa
    url: jdbc:h2:mem:testdb
  jpa:
    defer-datasource-initialization: 'true'
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: 'true'

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/realms/master

app:
  version: '@project.version@'
  name: '@project.name@'
server:
  port: '8081'

cors:
  originPatterns: 'https://*.github.io,http://localhost:5173'

